Aliaksei C: homework 2 done
eugene-okulik/ACQA pull request #1
Opened 2024-11-19 09:47 UTC by AliakseiChaban

2024-11-19 09:49 UTC, eugene-okulik requested changes
Как написано в задании, первый вариант не принимаю и указываю, что нужны изменения. Это просто для того, чтобы нам попрактиковаться в том, как мы будем взаимодействовать.
Добавь в файл какую-нибудь букву, коммитай и запушивай.

2024-11-19 10:10 UTC, AliakseiChaban commented
> Как написано в задании, первый вариант не принимаю и указываю, что нужны изменения. Это просто для того, чтобы нам попрактиковаться в том, как мы будем взаимодействовать. Добавь в файл какую-нибудь букву, коммитай и запушивай.

2024-11-19 10:10 UTC, AliakseiChaban commented
Done

2024-11-20 07:03 UTC, eugene-okulik approved these changes

2024-11-20 07:03 UTC, merged