Aliaksei C: homework_14 completed
eugene-okulik/ACQA pull request #13
Opened 2024-12-05 00:08 UTC by AliakseiChaban

2024-12-05 07:07 UTC, eugene-okulik requested changes
Отличное выполнение последней части задания. Но где запросы, которые это всё добавляют?

2024-12-05 07:16 UTC, AliakseiChaban commented
Доброе утро! Я что-то себе решил что важно только селекты отправить)

2024-12-05 17:59 UTC, eugene-okulik requested changes

2024-12-05 17:59 UTC, eugene-okulik commented on homework/aliaksei_chaban/homework_14/homework_14_DB.txt
> +INSERT INTO students (name, second_name, group_id) values ('Aleks', 'Chewbba', 2318);
Ты создал студента сразу с указанием группы, хотя группу создаешь позже. В задании написано

> Все действия нужно выполнить именно в том порядке, который указан здесь в задании.

2024-12-06 06:43 UTC, eugene-okulik approved these changes

2024-12-06 06:43 UTC, merged